name: super-exchange

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17.x'

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm test

      - name: Run Eslint
        run: npm run lint

      - name: Build
        run: npm run build --if-present

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'super-exchange-backend'
          heroku_email: ${{secrets.HEROKU_EMAIL}}
